"""full version3

Revision ID: 11e276c30de7
Revises: 6bd5f9828b8f
Create Date: 2021-09-16 14:48:54.219378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11e276c30de7'
down_revision = '6bd5f9828b8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('stop_informed_user_id', sa.Integer(), nullable=True),
    sa.Column('stop_deleted_user_id', sa.Integer(), nullable=True),
    sa.Column('stop_round', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.String(length=120), nullable=True),
    sa.Column('test_id', sa.String(length=120), nullable=True),
    sa.Column('test_indicator', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['stop_deleted_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['stop_informed_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stop_task_id'), 'stop', ['task_id'], unique=False)
    op.create_index(op.f('ix_stop_test_id'), 'stop', ['test_id'], unique=False)
    op.create_index(op.f('ix_stop_timestamp'), 'stop', ['timestamp'], unique=False)
    op.add_column('users', sa.Column('last_unread_stop_train_task_read_time', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('last_unread_stop_test_task_read_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_unread_stop_test_task_read_time')
    op.drop_column('users', 'last_unread_stop_train_task_read_time')
    op.drop_index(op.f('ix_stop_timestamp'), table_name='stop')
    op.drop_index(op.f('ix_stop_test_id'), table_name='stop')
    op.drop_index(op.f('ix_stop_task_id'), table_name='stop')
    op.drop_table('stop')
    # ### end Alembic commands ###
