"""version2

Revision ID: 21d30dc6c952
Revises: 482428aeb477
Create Date: 2021-12-08 22:04:07.676500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21d30dc6c952'
down_revision = '482428aeb477'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matched', sa.Column('task_mode', sa.String(length=120), nullable=True))
    op.add_column('matched', sa.Column('model_name', sa.String(length=120), nullable=True))
    op.add_column('matched', sa.Column('metric_name', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matched', 'metric_name')
    op.drop_column('matched', 'model_name')
    op.drop_column('matched', 'task_mode')
    # ### end Alembic commands ###
