"""update2

Revision ID: 300fc2078f00
Revises: ee161c2d04fc
Create Date: 2021-11-01 02:16:29.790013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '300fc2078f00'
down_revision = 'ee161c2d04fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matched', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('test_description', sa.String(length=500), nullable=True))

    with op.batch_alter_table('pending', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pending_task_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('pending_task_description', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending', schema=None) as batch_op:
        batch_op.drop_column('pending_task_description')
        batch_op.drop_column('pending_task_name')

    with op.batch_alter_table('matched', schema=None) as batch_op:
        batch_op.drop_column('test_description')
        batch_op.drop_column('test_name')

    # ### end Alembic commands ###
