"""ceshi

Revision ID: 384d339bded2
Revises: 92bbe8ad34dc
Create Date: 2021-06-03 15:09:02.419278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '384d339bded2'
down_revision = '92bbe8ad34dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_seen')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_seen', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
