"""fullversion2

Revision ID: 412ef25ec705
Revises: e361a2df9b84
Create Date: 2021-06-17 17:00:39.527777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '412ef25ec705'
down_revision = 'e361a2df9b84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matched', schema=None) as batch_op:
        batch_op.add_column(sa.Column('request_timestamp', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('match_id_timestamp', sa.DateTime(), nullable=True))
        batch_op.drop_index('ix_matched_timestamp')
        batch_op.create_index(batch_op.f('ix_matched_match_id_timestamp'), ['match_id_timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_matched_request_timestamp'), ['request_timestamp'], unique=False)
        batch_op.drop_column('timestamp')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('situation_timestamp', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('output_timestamp', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_messages_output_timestamp'), ['output_timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_situation_timestamp'), ['situation_timestamp'], unique=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_column('sender_random_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_matched_file_read_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_situation_read_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_output_read_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_output_read_time')
        batch_op.drop_column('last_situation_read_time')
        batch_op.drop_column('last_matched_file_read_time')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_random_id', sa.INTEGER(), nullable=True))

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_situation_timestamp'))
        batch_op.drop_index(batch_op.f('ix_messages_output_timestamp'))
        batch_op.drop_column('output_timestamp')
        batch_op.drop_column('situation_timestamp')

    with op.batch_alter_table('matched', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DATETIME(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_matched_request_timestamp'))
        batch_op.drop_index(batch_op.f('ix_matched_match_id_timestamp'))
        batch_op.create_index('ix_matched_timestamp', ['timestamp'], unique=False)
        batch_op.drop_column('match_id_timestamp')
        batch_op.drop_column('request_timestamp')

    # ### end Alembic commands ###
