"""ceshi2

Revision ID: 657c0b37f293
Revises: 384d339bded2
Create Date: 2021-06-03 15:41:11.468636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '657c0b37f293'
down_revision = '384d339bded2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_seen')

    # ### end Alembic commands ###
