"""full version2

Revision ID: 6bd5f9828b8f
Revises: e250a15a1138
Create Date: 2021-09-10 12:02:49.549180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bd5f9828b8f'
down_revision = 'e250a15a1138'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matched', sa.Column('Terminate', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matched', 'Terminate')
    # ### end Alembic commands ###
