"""full version3

Revision ID: 8bc1ec6c4bcd
Revises: 412ef25ec705
Create Date: 2021-06-18 13:36:36.503159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bc1ec6c4bcd'
down_revision = '412ef25ec705'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('situation', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('output', sa.Text(), nullable=True))

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('ix_notifications_task_id')
        batch_op.drop_column('task_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_id', sa.VARCHAR(length=120), nullable=True))
        batch_op.create_index('ix_notifications_task_id', ['task_id'], unique=False)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('output')
        batch_op.drop_column('situation')

    # ### end Alembic commands ###
