"""full version 8

Revision ID: ab774c235324
Revises: db62f04cc48b
Create Date: 2021-07-27 17:18:36.016478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab774c235324'
down_revision = 'db62f04cc48b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matched', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_id', sa.String(length=120), nullable=True))
        batch_op.create_index(batch_op.f('ix_matched_test_id'), ['test_id'], unique=False)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_id', sa.String(length=120), nullable=True))
        batch_op.create_index(batch_op.f('ix_messages_test_id'), ['test_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_test_id'))
        batch_op.drop_column('test_id')

    with op.batch_alter_table('matched', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_matched_test_id'))
        batch_op.drop_column('test_id')

    # ### end Alembic commands ###
