"""full version6

Revision ID: adcd907484df
Revises: d850f5ab038f
Create Date: 2021-07-08 16:06:07.381899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adcd907484df'
down_revision = 'd850f5ab038f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matched', schema=None) as batch_op:
        batch_op.add_column(sa.Column('matched_done', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matched', schema=None) as batch_op:
        batch_op.drop_column('matched_done')

    # ### end Alembic commands ###
