"""full_version7

Revision ID: db62f04cc48b
Revises: adcd907484df
Create Date: 2021-07-19 17:35:48.741409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db62f04cc48b'
down_revision = 'adcd907484df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matched', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_indicator', sa.String(length=10), nullable=True))

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_indicator', sa.String(length=10), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_test_requests_read_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_test_matched_file_read_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_test_output_read_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_test_output_read_time')
        batch_op.drop_column('last_test_matched_file_read_time')
        batch_op.drop_column('last_test_requests_read_time')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('test_indicator')

    with op.batch_alter_table('matched', schema=None) as batch_op:
        batch_op.drop_column('test_indicator')

    # ### end Alembic commands ###
