"""full version1

Revision ID: e361a2df9b84
Revises: 
Create Date: 2021-06-11 11:15:28.830878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e361a2df9b84'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matched', schema=None) as batch_op:
        batch_op.drop_column('recipient_id')
        batch_op.drop_column('recipient_random_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matched', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipient_random_id', sa.VARCHAR(length=120), nullable=True))
        batch_op.add_column(sa.Column('recipient_id', sa.VARCHAR(length=120), nullable=True))

    # ### end Alembic commands ###
