"""update

Revision ID: ee161c2d04fc
Revises: 
Create Date: 2021-11-01 01:53:47.288588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee161c2d04fc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matched',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.String(length=120), nullable=True),
    sa.Column('task_name', sa.String(length=120), nullable=True),
    sa.Column('task_description', sa.String(length=500), nullable=True),
    sa.Column('request_timestamp', sa.DateTime(), nullable=True),
    sa.Column('match_id_timestamp', sa.DateTime(), nullable=True),
    sa.Column('sponsor_id', sa.Integer(), nullable=True),
    sa.Column('assistor_id_pair', sa.Integer(), nullable=True),
    sa.Column('Matched_id_file', sa.Text(), nullable=True),
    sa.Column('matched_done', sa.Integer(), nullable=True),
    sa.Column('Assistor_matched_written_done', sa.String(length=120), nullable=True),
    sa.Column('sponsor_random_id', sa.String(length=120), nullable=True),
    sa.Column('assistor_random_id_pair', sa.String(length=120), nullable=True),
    sa.Column('test_indicator', sa.String(length=10), nullable=True),
    sa.Column('test_id', sa.String(length=120), nullable=True),
    sa.Column('Terminate', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('matched', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_matched_match_id_timestamp'), ['match_id_timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_matched_request_timestamp'), ['request_timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_matched_task_id'), ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_matched_test_id'), ['test_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.Column('about_me', sa.Text(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('last_requests_read_time', sa.DateTime(), nullable=True),
    sa.Column('last_matched_file_read_time', sa.DateTime(), nullable=True),
    sa.Column('last_situation_read_time', sa.DateTime(), nullable=True),
    sa.Column('last_output_read_time', sa.DateTime(), nullable=True),
    sa.Column('last_test_requests_read_time', sa.DateTime(), nullable=True),
    sa.Column('last_test_matched_file_read_time', sa.DateTime(), nullable=True),
    sa.Column('last_test_output_read_time', sa.DateTime(), nullable=True),
    sa.Column('last_messages_read_time', sa.DateTime(), nullable=True),
    sa.Column('last_unread_stop_train_task_read_time', sa.DateTime(), nullable=True),
    sa.Column('last_unread_stop_test_task_read_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('situation_timestamp', sa.DateTime(), nullable=True),
    sa.Column('output_timestamp', sa.DateTime(), nullable=True),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('sender_random_id', sa.String(length=120), nullable=True),
    sa.Column('assistor_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.String(length=120), nullable=True),
    sa.Column('rounds', sa.Integer(), nullable=True),
    sa.Column('situation', sa.Text(), nullable=True),
    sa.Column('output', sa.Text(), nullable=True),
    sa.Column('test_indicator', sa.String(length=10), nullable=True),
    sa.Column('test_id', sa.String(length=120), nullable=True),
    sa.Column('Sponsor_situation_training_done', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['assistor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_output_timestamp'), ['output_timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_situation_timestamp'), ['situation_timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_task_id'), ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_test_id'), ['test_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_timestamp'), ['timestamp'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('timestamp', sa.Float(), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('sender_random_id_list', sa.Text(), nullable=True),
    sa.Column('task_id_list', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_timestamp'), ['timestamp'], unique=False)

    op.create_table('pending',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('pending_assistor_id', sa.Integer(), nullable=True),
    sa.Column('pending_task_id', sa.String(length=120), nullable=True),
    sa.Column('pending_test_id', sa.String(length=120), nullable=True),
    sa.Column('test_indicator', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['pending_assistor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pending', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pending_pending_task_id'), ['pending_task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pending_pending_test_id'), ['pending_test_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pending_timestamp'), ['timestamp'], unique=False)

    op.create_table('stop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('stop_informed_user_id', sa.Integer(), nullable=True),
    sa.Column('stop_deleted_user_id', sa.Integer(), nullable=True),
    sa.Column('stop_round', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.String(length=120), nullable=True),
    sa.Column('test_id', sa.String(length=120), nullable=True),
    sa.Column('test_indicator', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['stop_deleted_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['stop_informed_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stop', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stop_task_id'), ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stop_test_id'), ['test_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stop_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stop', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stop_timestamp'))
        batch_op.drop_index(batch_op.f('ix_stop_test_id'))
        batch_op.drop_index(batch_op.f('ix_stop_task_id'))

    op.drop_table('stop')
    with op.batch_alter_table('pending', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pending_timestamp'))
        batch_op.drop_index(batch_op.f('ix_pending_pending_test_id'))
        batch_op.drop_index(batch_op.f('ix_pending_pending_task_id'))

    op.drop_table('pending')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_timestamp'))
        batch_op.drop_index(batch_op.f('ix_notifications_name'))

    op.drop_table('notifications')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_timestamp'))
        batch_op.drop_index(batch_op.f('ix_messages_test_id'))
        batch_op.drop_index(batch_op.f('ix_messages_task_id'))
        batch_op.drop_index(batch_op.f('ix_messages_situation_timestamp'))
        batch_op.drop_index(batch_op.f('ix_messages_output_timestamp'))

    op.drop_table('messages')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('matched', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_matched_test_id'))
        batch_op.drop_index(batch_op.f('ix_matched_task_id'))
        batch_op.drop_index(batch_op.f('ix_matched_request_timestamp'))
        batch_op.drop_index(batch_op.f('ix_matched_match_id_timestamp'))

    op.drop_table('matched')
    # ### end Alembic commands ###
